name: Create and publish a Docker images

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push chatgpt_web
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/chatgpt_web:latest

    - name: Build and push mocked_api
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./mocked_api/Dockerfile-mockapi
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/chatgpt_api:latest